### ISSUE TITLE
Remote notifications

### ISSUE THREAD

**Issue by diegogarciar** [Vanethos/flutter_notification_permissions#21]
Hey it would be good if we had the option to also register users for remote notifications on iOS
`application.registerForRemoteNotifications()`

**Comment by Vanethos** [comment]
This is out of the scope for this plugin, since the objective is to know what is the status of the notifcation permission

**Comment by diegogarciar** [comment]
Well, the readme description states otherwise:

> Package to check for and ask for Notification Permissions on iOS and Android.

with two main functionalities of the library,
[Checking Notification Permission Status](https://github.com/Vanethos/flutter_notification_permissions#checking-notification-permission-status) and [Requesting Notification Permissions](https://github.com/Vanethos/flutter_notification_permissions#requesting-notification-permissions)

In my opinion it's a dealbreaker to have to look for another package just to enable remote notifications. 

I think it would be as simple as having another option on the iOS Settings asking if remote notifications should also be enabled
