### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by Aulig** [Vanethos/flutter_notification_permissions#34]
Hey,
just wanted to check in if you're already working on migrating to null safety. Or are you waiting on a dependency to migrate?

**Comment by anoop4real** [comment]
In my app, this is the only package which is not null safe, any plans on migration soon?

**Comment by Aulig** [comment]
Thanks for your PR @anoop4real Would be awesome if you could check https://github.com/Vanethos/flutter_notification_permissions/pull/36 out @Vanethos 
Thank you!

**Comment by anoop4real** [comment]
@Aulig For the time being may be you can use my fork, add below in pubspec.yaml, then it will use my fork, may be you can also test my changes and as a note once the PR is approved make sure you put back the original as I might not be maintaining this further.

`  notification_permissions:
    git:
      url: https://github.com/anoop4real/flutter_notification_permissions`

**Comment by Aulig** [comment]
Thanks again @anoop4real! I've tested it, everything seems to be working in my app on Android and iOS.

**Comment by anoop4real** [comment]
Great hope the PR gets approved soon

**Comment by Vanethos** [comment]
Approved, in a couple of hours I'll get the new version up, thanks you @Aulig and @anoop4real !

**Comment by Aulig** [comment]
Awesome, thank you!

**Comment by levent-kantaroglu** [comment]
It will be also deployed to pub.dev

**Comment by anoop4real** [comment]
@Vanethos Thanks a lot for approving. Forgot to mention, I was getting deprecation warning from one of the .java file (I think it was for Android), it is worth looking into that also if you have time

**Comment by Vanethos** [comment]
@anoop4real at the end of this month I'll carve some time for that if I can :D
