### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by JoeCiou** [Vanethos/flutter_notification_permissions#6]
I got the error when I build my iOS app with notification_permissions

```
'notification_permissions/notification_permissions-Swift.h' file not found
    #import <notification_permissions/notification_permissions-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

How to fix this issue?

**Comment by Vanethos** [comment]
I've opened issue #7  and will work on it as soon as possible.

The problem is the incompability with Swift and Objective-C projects

**Comment by Vanethos** [comment]
@JoeCiou 

Please follow this SO answer and update the file

https://stackoverflow.com/a/53453243/4499889

This should solve the problem

**Comment by JoeCiou** [comment]
> @JoeCiou
> 
> Please follow this SO answer and update the file
> 
> https://stackoverflow.com/a/53453243/4499889
> 
> This should solve the problem

Yes! This is work for me. thank you!
